spring.application.name=movie-ticket-booking-be
server.port=8080

app.frontend.host=http://localhost
app.frontend.port=3000

# MariaDB for Docker
spring.datasource.url=jdbc:mariadb://mariadb:3306/db_movie_ticket_booking?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

## JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Dialect cho MariaDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# SECURITY
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=31536000000

# Mail SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# AWS S3 Configuration
aws.s3.access-key=${AWS_ACCESS_KEY}
aws.s3.secret-key=${AWS_SECRET_KEY}
aws.s3.region=ap-southeast-1
aws.s3.bucket-name=go-cinema

# Actuator endpoints for health check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Backend config
app.backend.host=http://localhost
app.backend.expose_port=8080

# VNPay Configuration
app.vnp.ip.address=127.0.0.1